apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '7'
    field.cattle.io/publicEndpoints: >-
      [{"addresses":["128.55.206.106"],"port":443,"protocol":"HTTPS","serviceName":"iaas-gnn4itk:grafana","ingressName":"iaas-gnn4itk:ingress-grafana","hostname":"iaasdemo.ml4phys.com","path":"/grafana","allNodes":true},{"addresses":["128.55.206.106"],"port":443,"protocol":"HTTPS","serviceName":"iaas-gnn4itk:grafana","ingressName":"iaas-gnn4itk:ingress-grafana","hostname":"ingress-grafana.iaas-gnn4itk.production.svc.spin.nersc.org","path":"/","allNodes":true}]
    nersc.gov/collab_uids: ''
    nersc.gov/gid: '76739'
    nersc.gov/gids: >-
      4871,53006,57596,72330,76739,49584,78767,78781,81765,74560,95991,96414,103452,103453,110987
    nersc.gov/roles: user
    nersc.gov/uid: '76739'
    nersc.gov/username: xju
  creationTimestamp: '2025-09-12T05:47:20Z'
  generation: 13
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-iaas-gnn4itk-grafana
  managedFields:
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:field.cattle.io/publicEndpoints: {}
          f:labels:
            .: {}
            f:workload.user.cattle.io/workloadselector: {}
        f:spec:
          f:progressDeadlineSeconds: {}
          f:replicas: {}
          f:revisionHistoryLimit: {}
          f:selector: {}
          f:strategy:
            f:rollingUpdate:
              .: {}
              f:maxSurge: {}
              f:maxUnavailable: {}
            f:type: {}
          f:template:
            f:metadata:
              f:labels:
                .: {}
                f:workload.user.cattle.io/workloadselector: {}
              f:namespace: {}
            f:spec:
              f:containers:
                k:{"name":"container-0"}:
                  .: {}
                  f:env:
                    .: {}
                    k:{"name":"GF_DISABLE_SANITIZE_HTML"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"GF_SERVER_ROOT_URL"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"GF_SERVER_SERVE_FROM_SUB_PATH"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"KUBERNETES_CLUSTER_DOMAIN"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                  f:image: {}
                  f:imagePullPolicy: {}
                  f:name: {}
                  f:ports:
                    .: {}
                    k:{"containerPort":3000,"protocol":"TCP"}:
                      .: {}
                      f:containerPort: {}
                      f:name: {}
                      f:protocol: {}
                  f:resources: {}
                  f:securityContext:
                    .: {}
                    f:allowPrivilegeEscalation: {}
                    f:capabilities:
                      .: {}
                      f:drop: {}
                    f:privileged: {}
                    f:readOnlyRootFilesystem: {}
                    f:runAsNonRoot: {}
                  f:terminationMessagePath: {}
                  f:terminationMessagePolicy: {}
                  f:volumeMounts:
                    .: {}
                    k:{"mountPath":"/var/lib/grafana"}:
                      .: {}
                      f:mountPath: {}
                      f:name: {}
              f:dnsPolicy: {}
              f:restartPolicy: {}
              f:schedulerName: {}
              f:securityContext: {}
              f:terminationGracePeriodSeconds: {}
              f:volumes:
                .: {}
                k:{"name":"vol-vo5fg"}:
                  .: {}
                  f:name: {}
                  f:persistentVolumeClaim:
                    .: {}
                    f:claimName: {}
      manager: agent
      operation: Update
      time: '2025-09-12T18:54:32Z'
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:deployment.kubernetes.io/revision: {}
        f:status:
          f:availableReplicas: {}
          f:conditions:
            .: {}
            k:{"type":"Available"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"Progressing"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
          f:observedGeneration: {}
          f:readyReplicas: {}
          f:replicas: {}
          f:updatedReplicas: {}
      manager: kube-controller-manager
      operation: Update
      subresource: status
      time: '2025-09-12T18:54:32Z'
  name: grafana
  namespace: iaas-gnn4itk
  resourceVersion: '1009343052'
  uid: bd04bfc4-fa30-4d1a-869c-31e2428041ca
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-iaas-gnn4itk-grafana
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        nersc.gov/collab_uids: ''
        nersc.gov/gid: '76739'
        nersc.gov/gids: >-
          4871,53006,57596,72330,76739,49584,78767,78781,81765,74560,95991,96414,103452,103453,110987
        nersc.gov/roles: user
        nersc.gov/uid: '76739'
        nersc.gov/username: xju
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-iaas-gnn4itk-grafana
      namespace: iaas-gnn4itk
    spec:
      containers:
        - env:
            - name: GF_DISABLE_SANITIZE_HTML
              value: 'true'
            - name: KUBERNETES_CLUSTER_DOMAIN
              value: cluster.local
            - name: GF_SERVER_ROOT_URL
              value: '%(protocol)s://%(domain)s/grafana/'
            - name: GF_SERVER_SERVE_FROM_SUB_PATH
              value: 'true'
          image: grafana/grafana-oss:11.6.0
          imagePullPolicy: Always
          name: container-0
          ports:
            - containerPort: 3000
              name: portal
              protocol: TCP
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: vol-vo5fg
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: vol-vo5fg
          persistentVolumeClaim:
            claimName: grafana-data
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2025-09-12T05:47:29Z'
      lastUpdateTime: '2025-09-12T05:47:29Z'
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
    - lastTransitionTime: '2025-09-12T05:47:20Z'
      lastUpdateTime: '2025-09-12T17:03:57Z'
      message: ReplicaSet "grafana-67cc6d7fd5" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: 'True'
      type: Progressing
  observedGeneration: 13
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
