apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '15'
    nersc.gov/collab_uids: ''
    nersc.gov/gid: '76739'
    nersc.gov/gids: >-
      4871,53006,57596,72330,76739,49584,78767,78781,81765,74560,95991,96414,103452,103453,110987
    nersc.gov/roles: user
    nersc.gov/uid: '76739'
    nersc.gov/username: xju
  creationTimestamp: '2025-09-11T23:34:57Z'
  generation: 15
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-iaas-gnn4itk-prometheus
  managedFields:
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:workload.user.cattle.io/workloadselector: {}
        f:spec:
          f:progressDeadlineSeconds: {}
          f:replicas: {}
          f:revisionHistoryLimit: {}
          f:selector: {}
          f:strategy:
            f:rollingUpdate:
              .: {}
              f:maxSurge: {}
              f:maxUnavailable: {}
            f:type: {}
          f:template:
            f:metadata:
              f:annotations:
                f:cattle.io/timestamp: {}
              f:labels:
                .: {}
                f:workload.user.cattle.io/workloadselector: {}
              f:namespace: {}
            f:spec:
              f:affinity: {}
              f:containers:
                k:{"name":"container-0"}:
                  .: {}
                  f:args: {}
                  f:command: {}
                  f:image: {}
                  f:imagePullPolicy: {}
                  f:name: {}
                  f:ports:
                    .: {}
                    k:{"containerPort":9090,"protocol":"TCP"}:
                      .: {}
                      f:containerPort: {}
                      f:name: {}
                      f:protocol: {}
                  f:resources: {}
                  f:securityContext:
                    .: {}
                    f:allowPrivilegeEscalation: {}
                    f:capabilities:
                      .: {}
                      f:drop: {}
                    f:privileged: {}
                    f:readOnlyRootFilesystem: {}
                    f:runAsNonRoot: {}
                    f:runAsUser: {}
                  f:terminationMessagePath: {}
                  f:terminationMessagePolicy: {}
                  f:volumeMounts:
                    .: {}
                    k:{"mountPath":"/prometheus"}:
                      .: {}
                      f:mountPath: {}
                      f:name: {}
              f:dnsPolicy: {}
              f:restartPolicy: {}
              f:schedulerName: {}
              f:securityContext:
                .: {}
                f:fsGroup: {}
              f:terminationGracePeriodSeconds: {}
              f:volumes:
                .: {}
                k:{"name":"vol-a7k9l"}:
                  .: {}
                  f:hostPath:
                    .: {}
                    f:path: {}
                    f:type: {}
                  f:name: {}
      manager: agent
      operation: Update
      time: '2025-09-12T05:16:11Z'
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:deployment.kubernetes.io/revision: {}
        f:status:
          f:availableReplicas: {}
          f:conditions:
            .: {}
            k:{"type":"Available"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"Progressing"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
          f:observedGeneration: {}
          f:readyReplicas: {}
          f:replicas: {}
          f:updatedReplicas: {}
      manager: kube-controller-manager
      operation: Update
      subresource: status
      time: '2025-09-12T06:01:00Z'
  name: prometheus
  namespace: iaas-gnn4itk
  resourceVersion: '1008908019'
  uid: b13e7144-2c85-4079-bc3c-5274cc80f3cb
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-iaas-gnn4itk-prometheus
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: '2025-09-12T05:16:11Z'
        nersc.gov/collab_uids: ''
        nersc.gov/gid: '76739'
        nersc.gov/gids: >-
          4871,53006,57596,72330,76739,49584,78767,78781,81765,74560,95991,96414,103452,103453,110987
        nersc.gov/roles: user
        nersc.gov/uid: '76739'
        nersc.gov/username: xju
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-iaas-gnn4itk-prometheus
      namespace: iaas-gnn4itk
    spec:
      affinity: {}
      containers:
        - args:
            - '--config.file=/prometheus/config.yaml'
            - '--storage.tsdb.path=/prometheus'
          command:
            - /bin/prometheus
          image: prom/prometheus:v3.3.0
          imagePullPolicy: Always
          name: container-0
          ports:
            - containerPort: 9090
              name: prometheus
              protocol: TCP
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 76739
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /prometheus
              name: vol-a7k9l
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 76739
        runAsGroup: 76739
        runAsUser: 76739
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /global/cfs/cdirs/m2845/prometheus
            type: Directory
          name: vol-a7k9l
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2025-09-12T05:55:54Z'
      lastUpdateTime: '2025-09-12T05:55:54Z'
      message: ReplicaSet "prometheus-5d796df99f" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: 'True'
      type: Progressing
    - lastTransitionTime: '2025-09-12T06:01:00Z'
      lastUpdateTime: '2025-09-12T06:01:00Z'
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
  observedGeneration: 15
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
